### ISSUE TITLE
500 errors on EQ pre-prod

### ISSUE THREAD

**Issue by samiwel** [ONSdigital/eq-survey-runner#1288]
### Actual behaviour
Observed following error in the log:

```
[2017-10-06 07:47:35,235] ERROR in app: Exception on /questionnaire/1/0112/xqPDc9Sf/rsi/0/significant-change [POST]
Traceback (most recent call last):
File "/opt/python/run/venv/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
context)
File "/opt/python/run/venv/lib64/python3.4/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
cursor.execute(statement, parameters)
psycopg2.OperationalError: SSL SYSCALL error: EOF detected
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/opt/python/run/venv/lib/python3.4/site-packages/flask/app.py", line 1610, in full_dispatch_request
rv = self.preprocess_request()
File "/opt/python/run/venv/lib/python3.4/site-packages/flask/app.py", line 1831, in preprocess_request
rv = func()
File "/opt/python/current/app/app/views/questionnaire.py", line 44, in before_request
metadata = get_metadata(current_user)
File "/opt/python/current/app/app/globals.py", line 22, in get_metadata
if user.is_anonymous:
File "/opt/python/run/venv/lib/python3.4/site-packages/werkzeug/local.py", line 347, in __getattr__
return getattr(self._get_current_object(), name)
File "/opt/python/run/venv/lib/python3.4/site-packages/werkzeug/local.py", line 306, in _get_current_object
return self.__local()
File "/opt/python/run/venv/lib/python3.4/site-packages/flask_login.py", line 47, in <lambda>
current_user = LocalProxy(lambda: _get_user())
File "/opt/python/run/venv/lib/python3.4/site-packages/flask_login.py", line 858, in _get_user
current_app.login_manager._load_user()
File "/opt/python/run/venv/lib/python3.4/site-packages/flask_login.py", line 385, in _load_user
return self._load_from_request(request)
File "/opt/python/run/venv/lib/python3.4/site-packages/flask_login.py", line 451, in _load_from_request
user = self.request_callback(request)
File "/opt/python/current/app/app/authentication/authenticator.py", line 28, in request_load_user
return load_user()
File "/opt/python/current/app/app/authentication/authenticator.py", line 36, in load_user
user_id = current_app.eq['session_storage'].get_user_id()
File "/opt/python/current/app/app/authentication/session_storage.py", line 54, in get_user_id
eq_session = self._get_user_session(eq_session_id)
File "/opt/python/current/app/app/authentication/session_storage.py", line 66, in _get_user_session
eq_session = EQSession.query.filter(EQSession.eq_session_id == eq_session_id).first()
File "/opt/python/run/venv/lib64/python3.4/site-packages/sqlalchemy/orm/query.py", line 2634, in first
ret = list(self[0:1])
File "/opt/python/run/venv/lib64/python3.4/site-packages/sqlalchemy/orm/query.py", line 2457, in __getitem__
return list(res)
File "/opt/python/run/venv/lib64/python3.4/site-packages/sqlalchemy/orm/query.py", line 2736, in __iter__
return self._execute_and_instances(context)
File "/opt/python/run/venv/lib64/python3.4/site-packages/sqlalchemy/orm/query.py", line 2751, in _execute_and_instances
result = conn.execute(querycontext.statement, self._params)
File "/opt/python/run/venv/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 914, in execute
return meth(self, multiparams, params)
File "/opt/python/run/venv/lib64/python3.4/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
return connection._execute_clauseelement(self, multiparams, params)
File "/opt/python/run/venv/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
compiled_sql, distilled_params
File "/opt/python/run/venv/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
context)
File "/opt/python/run/venv/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
exc_info
File "/opt/python/run/venv/lib64/python3.4/site-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
reraise(type(exception), exception, tb=exc_tb, cause=cause)
File "/opt/python/run/venv/lib64/python3.4/site-packages/sqlalchemy/util/compat.py", line 183, in reraise
raise value.with_traceback(tb)
File "/opt/python/run/venv/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
context)
File "/opt/python/run/venv/lib64/python3.4/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) SSL SYSCALL error: EOF detected
[SQL: 'SELECT eq_session.eq_session_id AS eq_session_eq_session_id, eq_session.user_id AS eq_session_user_id, on.eq_session_id = %(eq_session_id_1)s \\n LIMIT %(param_1)s'] [parameters: {'eq_session_id_1': During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/opt/python/run/venv/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 1069, in _execute_context
conn = self.__connection
AttributeError: 'Connection' object has no attribute '_Connection__connection'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/opt/python/run/venv/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 1071, in _execute_context
conn = self._revalidate_connection()
File "/opt/python/run/venv/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 391, in _revalidate_connection
"Can't reconnect until invalid "
sqlalchemy.exc.InvalidRequestError: Can't reconnect until invalid transaction is rolled back
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/opt/python/run/venv/lib/python3.4/site-packages/flask/app.py", line 1982, in wsgi_app
response = self.full_dispatch_request()
File "/opt/python/run/venv/lib/python3.4/site-packages/flask/app.py", line 1614, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/opt/python/run/venv/lib/python3.4/site-packages/flask/app.py", line 1518, in handle_user_exception
return handler(e)
File "/opt/python/current/app/app/views/errors.py", line 58, in internal_server_error
log_exception(error, 500)
File "/opt/python/current/app/app/views/errors.py", line 70, in log_exception
metadata = get_metadata(current_user)
File "/opt/python/current/app/app/globals.py", line 22, in get_metadata
if user.is_anonymous:
File "/opt/python/run/venv/lib/python3.4/site-packages/werkzeug/local.py", line 347, in __getattr__
return getattr(self._get_current_object(), name)
File "/opt/python/run/venv/lib/python3.4/site-packages/werkzeug/local.py", line 306, in _get_current_object
return self.__local()
File "/opt/python/run/venv/lib/python3.4/site-packages/flask_login.py", line 47, in <lambda>
current_user = LocalProxy(lambda: _get_user())
File "/opt/python/run/venv/lib/python3.4/site-packages/flask_login.py", line 858, in _get_user
current_app.login_manager._load_user()
File "/opt/python/run/venv/lib/python3.4/site-packages/flask_login.py", line 385, in _load_user
return self._load_from_request(request)
File "/opt/python/run/venv/lib/python3.4/site-packages/flask_login.py", line 451, in _load_from_request
user = self.request_callback(request)
File "/opt/python/current/app/app/authentication/authenticator.py", line 28, in request_load_user
return load_user()
File "/opt/python/current/app/app/authentication/authenticator.py", line 36, in load_user
user_id = current_app.eq['session_storage'].get_user_id()
File "/opt/python/current/app/app/authentication/session_storage.py", line 54, in get_user_id
eq_session = self._get_user_session(eq_session_id)
File "/opt/python/current/app/app/authentication/session_storage.py", line 66, in _get_user_session
eq_session = EQSession.query.filter(EQSession.eq_session_id == eq_session_id).first()
File "/opt/python/run/venv/lib64/python3.4/site-packages/sqlalchemy/orm/query.py", line 2634, in first
ret = list(self[0:1])
File "/opt/python/run/venv/lib64/python3.4/site-packages/sqlalchemy/orm/query.py", line 2457, in __getitem__
return list(res)
File "/opt/python/run/venv/lib64/python3.4/site-packages/sqlalchemy/orm/query.py", line 2736, in __iter__
return self._execute_and_instances(context)
File "/opt/python/run/venv/lib64/python3.4/site-packages/sqlalchemy/orm/query.py", line 2751, in _execute_and_instances
result = conn.execute(querycontext.statement, self._params)
File "/opt/python/run/venv/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 914, in execute
return meth(self, multiparams, params)
File "/opt/python/run/venv/lib64/python3.4/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
return connection._execute_clauseelement(self, multiparams, params)
File "/opt/python/run/venv/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
compiled_sql, distilled_params
File "/opt/python/run/venv/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 1078, in _execute_context
None, None)
File "/opt/python/run/venv/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
exc_info
File "/opt/python/run/venv/lib64/python3.4/site-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
reraise(type(exception), exception, tb=exc_tb, cause=cause)
File "/opt/python/run/venv/lib64/python3.4/site-packages/sqlalchemy/util/compat.py", line 183, in reraise
raise value.with_traceback(tb)
File "/opt/python/run/venv/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 1071, in _execute_context
conn = self._revalidate_connection()
File "/opt/python/run/venv/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 391, in _revalidate_connection
"Can't reconnect until invalid "
sqlalchemy.exc.StatementError: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back [SQL: 'SELECT eq_session.eq_session_id AS eq_session_eq_session_id, eq_session.user_id AS eq_session_user_id, eq_session.timestamp AS eq_session_timestamp \\nFROM eq_session \\nWHERE eq_session.eq_session_id = %(eq_session_id_1)s \\n LIMIT %(param_1)s'] [parameters: [immutabledict(
{}
)]]
```

**Comment by ajmaddaford** [comment]
This looks like it might be related to https://github.com/psycopg/psycopg2/issues/263
This issue was resolved in https://github.com/psycopg/psycopg2/pull/446 and released in 2.6.2, but the fix was regressed in the 2.7 releases until 2.7.2. 

We're using version 2.6.1 of psycopg2, so we should look to upgrade to the latest 2.7 release.
