### ISSUE TITLE
Survey from URL failed to load schema on thank you page

### ISSUE THREAD

**Issue by jonnyshaw89** [ONSdigital/eq-survey-runner#1328]
### Expected behaviour
When loading a survey from a URL, on completing the survey you should be presented with the thank you page

### Actual behaviour
The thank you page fails to load as it attempts to load the survey json from file.

### Steps to reproduce the behaviour
Preview from author and submit the survey

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.4/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/src/app/app/views/questionnaire.py", line 175, in get_thank_you
    schema = load_schema_from_params(eq_id, form_type)
  File "/usr/local/lib/python3.4/site-packages/flask_caching/__init__.py", line 674, in decorated_function
    rv = f(*args, **kwargs)
  File "/usr/src/app/app/utilities/schema.py", line 24, in load_schema_from_params
    return load_schema_file('{}_{}.json'.format(eq_id, form_type), language_code)
  File "/usr/src/app/app/utilities/schema.py", line 49, in load_schema_file
    raise e
  File "/usr/src/app/app/utilities/schema.py", line 44, in load_schema_file
    with open(schema_path, encoding='utf8') as json_data:
FileNotFoundError: [Errno 2] No such file or directory: 'data/en/2_2.json'
```

**Comment by dwyeradam** [comment]
@jonnyshaw89 I believe this is the same as Issue #1442. If so can it now be closed as that has been fixed?

**Comment by nealedj** [comment]
Good shout.
