### ISSUE TITLE
Cannot run more than one Selenium test in parallel

### ISSUE THREAD

**Issue by hamishtaplin** [ONSdigital/eq-survey-runner#329]
### Expected behaviour
- Selenium tests should be able to run multiple tests/browsers in parallel.
### Actual behaviour
- Running more than one test in parallel causes an application error.
### Steps to reproduce the behaviour
- `npm install`
- Change [wdio config file](https://github.com/ONSdigital/eq-survey-runner/blob/master/tests/wdio/config.js#L20) to run with more than one browser, eg: 

``` javascript
capabilities: [{
    name: 'Chrome (local)',
    browserName: 'chrome'
  }, {
    name: 'Firefox (local)',
    browserName: 'firefox'
  }],
```
- `npm run test_functional`
- one browser will complete the test first, causing the other to stall and then eventually fail.
- Selenium will timeout

**NOTE: [User ID is randomly generated](https://github.com/ONSdigital/eq-survey-runner/blob/master/tests/wdio/spec/mci.spec.js#L12) in the test so they are running as different users** 
### Screenshot

<img width="1243" alt="screenshot 2016-07-21 15 37 21" src="https://cloud.githubusercontent.com/assets/930398/17026753/15bbcbf0-4f59-11e6-994d-73312eba57ec.png">

**Comment by hamishtaplin** [comment]
Console output:

```
Traceback (most recent call last):
  File "/Users/hamishtaplin/.virtualenvs/eq-survey-runner/lib/python3.5/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/hamishtaplin/Sites/eq-survey-runner/app/__init__.py", line 94, in __call__
    return self.app(environ, start_response)
  File "/Users/hamishtaplin/.virtualenvs/eq-survey-runner/lib/python3.5/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/hamishtaplin/.virtualenvs/eq-survey-runner/lib/python3.5/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/hamishtaplin/.virtualenvs/eq-survey-runner/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/hamishtaplin/.virtualenvs/eq-survey-runner/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/hamishtaplin/.virtualenvs/eq-survey-runner/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/hamishtaplin/.virtualenvs/eq-survey-runner/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/hamishtaplin/.virtualenvs/eq-survey-runner/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/hamishtaplin/.virtualenvs/eq-survey-runner/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/hamishtaplin/.virtualenvs/eq-survey-runner/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/hamishtaplin/.virtualenvs/eq-survey-runner/lib/python3.5/site-packages/flask_login.py", line 790, in decorated_view
    elif not current_user.is_authenticated:
  File "/Users/hamishtaplin/.virtualenvs/eq-survey-runner/lib/python3.5/site-packages/werkzeug/local.py", line 343, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/Users/hamishtaplin/.virtualenvs/eq-survey-runner/lib/python3.5/site-packages/werkzeug/local.py", line 302, in _get_current_object
    return self.__local()
  File "/Users/hamishtaplin/.virtualenvs/eq-survey-runner/lib/python3.5/site-packages/flask_login.py", line 47, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "/Users/hamishtaplin/.virtualenvs/eq-survey-runner/lib/python3.5/site-packages/flask_login.py", line 858, in _get_user
    current_app.login_manager._load_user()
  File "/Users/hamishtaplin/.virtualenvs/eq-survey-runner/lib/python3.5/site-packages/flask_login.py", line 385, in _load_user
    return self._load_from_request(request)
  File "/Users/hamishtaplin/.virtualenvs/eq-survey-runner/lib/python3.5/site-packages/flask_login.py", line 451, in _load_from_request
    user = self.request_callback(request)
  File "/Users/hamishtaplin/Sites/eq-survey-runner/app/__init__.py", line 82, in request_load_user
    return authenticator.check_session()
  File "/Users/hamishtaplin/Sites/eq-survey-runner/app/authentication/authenticator.py", line 28, in check_session
    metadata = MetaDataStore.get_instance(user)
  File "/Users/hamishtaplin/Sites/eq-survey-runner/app/metadata/metadata_store.py", line 118, in get_instance
    raise RuntimeError("No metadata for user %s", user.get_user_id())
RuntimeError: ('No metadata for user %s', '4bd5e32b44dfa735720778ce311fff2b223a46ec54866933657ce6b9efee6c9c')
```

**Comment by warrenbailey** [comment]
The user id is a combination of the eq_id, form_type, ru_ref and collection_exersise_sid. It's not the user id field anymore. I reckon that this error is because they are now running as the same user, and the error occurs when one of them submits wiping the data for the others.

If we randomise the collection exercise sid rather than the user id field on the dev page it might work again

**Comment by hamishtaplin** [comment]
@warrenbailey Can it be any string?

**Comment by hamishtaplin** [comment]
@warrenbailey yep that fixes it 👍
